server:
  port: 1001
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defalut-Zone: http://${eureka.instance.hostname}:8761/eureka
spring:
  application:
    name: microservice-100-order